//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENI) DeepCopyInto(out *NodeENI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENI.
func (in *NodeENI) DeepCopy() *NodeENI {
	if in == nil {
		return nil
	}
	out := new(NodeENI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeENI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENIList) DeepCopyInto(out *NodeENIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeENI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENIList.
func (in *NodeENIList) DeepCopy() *NodeENIList {
	if in == nil {
		return nil
	}
	out := new(NodeENIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeENIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfig) DeepCopyInto(out *NodeSystemConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfig.
func (in *NodeSystemConfig) DeepCopy() *NodeSystemConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigList) DeepCopyInto(out *NodeSystemConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSystemConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigList.
func (in *NodeSystemConfigList) DeepCopy() *NodeSystemConfigList {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENISpec) DeepCopyInto(out *NodeENISpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetNames != nil {
		in, out := &in.SubnetNames, &out.SubnetNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupNames != nil {
		in, out := &in.SecurityGroupNames, &out.SecurityGroupNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENISpec.
func (in *NodeENISpec) DeepCopy() *NodeENISpec {
	if in == nil {
		return nil
	}
	out := new(NodeENISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENIStatus) DeepCopyInto(out *NodeENIStatus) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]ENIAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENIStatus.
func (in *NodeENIStatus) DeepCopy() *NodeENIStatus {
	if in == nil {
		return nil
	}
	out := new(NodeENIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ENIAttachment) DeepCopyInto(out *ENIAttachment) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ENIAttachment.
func (in *ENIAttachment) DeepCopy() *ENIAttachment {
	if in == nil {
		return nil
	}
	out := new(ENIAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigSpec) DeepCopyInto(out *NodeSystemConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HugePagesConfig != nil {
		in, out := &in.HugePagesConfig, &out.HugePagesConfig
		*out = new(HugePagesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SysctlConfig != nil {
		in, out := &in.SysctlConfig, &out.SysctlConfig
		*out = new(SysctlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelModulesConfig != nil {
		in, out := &in.KernelModulesConfig, &out.KernelModulesConfig
		*out = new(KernelModulesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUConfig != nil {
		in, out := &in.CPUConfig, &out.CPUConfig
		*out = new(CPUConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryConfig != nil {
		in, out := &in.MemoryConfig, &out.MemoryConfig
		*out = new(MemoryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigSpec.
func (in *NodeSystemConfigSpec) DeepCopy() *NodeSystemConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigStatus) DeepCopyInto(out *NodeSystemConfigStatus) {
	*out = *in
	if in.Configurations != nil {
		in, out := &in.Configurations, &out.Configurations
		*out = make([]SystemConfigStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigStatus.
func (in *NodeSystemConfigStatus) DeepCopy() *NodeSystemConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigStatus)
	in.DeepCopyInto(out)
	return out
}
