//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUConfig) DeepCopyInto(out *CPUConfig) {
	*out = *in
	if in.TurboBoost != nil {
		in, out := &in.TurboBoost, &out.TurboBoost
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUConfig.
func (in *CPUConfig) DeepCopy() *CPUConfig {
	if in == nil {
		return nil
	}
	out := new(CPUConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStatus) DeepCopyInto(out *CPUStatus) {
	*out = *in
	if in.TurboBoost != nil {
		in, out := &in.TurboBoost, &out.TurboBoost
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStatus.
func (in *CPUStatus) DeepCopy() *CPUStatus {
	if in == nil {
		return nil
	}
	out := new(CPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ENIAttachment) DeepCopyInto(out *ENIAttachment) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ENIAttachment.
func (in *ENIAttachment) DeepCopy() *ENIAttachment {
	if in == nil {
		return nil
	}
	out := new(ENIAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePageMemoryInfo) DeepCopyInto(out *HugePageMemoryInfo) {
	*out = *in
	if in.FragmentationLevel != nil {
		in, out := &in.FragmentationLevel, &out.FragmentationLevel
		*out = new(int32)
		**out = **in
	}
	if in.NUMANodes != nil {
		in, out := &in.NUMANodes, &out.NUMANodes
		*out = make([]NUMANodeMemoryInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePageMemoryInfo.
func (in *HugePageMemoryInfo) DeepCopy() *HugePageMemoryInfo {
	if in == nil {
		return nil
	}
	out := new(HugePageMemoryInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePageRetryPolicy) DeepCopyInto(out *HugePageRetryPolicy) {
	*out = *in
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.BackoffMultiplier != nil {
		in, out := &in.BackoffMultiplier, &out.BackoffMultiplier
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePageRetryPolicy.
func (in *HugePageRetryPolicy) DeepCopy() *HugePageRetryPolicy {
	if in == nil {
		return nil
	}
	out := new(HugePageRetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePageSpec) DeepCopyInto(out *HugePageSpec) {
	*out = *in
	if in.NUMANode != nil {
		in, out := &in.NUMANode, &out.NUMANode
		*out = new(int32)
		**out = **in
	}
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int32)
		**out = **in
	}
	if in.AllowPartialAllocation != nil {
		in, out := &in.AllowPartialAllocation, &out.AllowPartialAllocation
		*out = new(bool)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePageSpec.
func (in *HugePageSpec) DeepCopy() *HugePageSpec {
	if in == nil {
		return nil
	}
	out := new(HugePageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePageStatus) DeepCopyInto(out *HugePageStatus) {
	*out = *in
	if in.NUMANode != nil {
		in, out := &in.NUMANode, &out.NUMANode
		*out = new(int32)
		**out = **in
	}
	in.LastAllocationAttempt.DeepCopyInto(&out.LastAllocationAttempt)
	if in.AllocationErrors != nil {
		in, out := &in.AllocationErrors, &out.AllocationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.PartialAllocationAccepted != nil {
		in, out := &in.PartialAllocationAccepted, &out.PartialAllocationAccepted
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePageStatus.
func (in *HugePageStatus) DeepCopy() *HugePageStatus {
	if in == nil {
		return nil
	}
	out := new(HugePageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePagesConfig) DeepCopyInto(out *HugePagesConfig) {
	*out = *in
	if in.Pages != nil {
		in, out := &in.Pages, &out.Pages
		*out = make([]HugePageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreAllocationCheck != nil {
		in, out := &in.PreAllocationCheck, &out.PreAllocationCheck
		*out = new(bool)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(HugePageRetryPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePagesConfig.
func (in *HugePagesConfig) DeepCopy() *HugePagesConfig {
	if in == nil {
		return nil
	}
	out := new(HugePagesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugePagesStatus) DeepCopyInto(out *HugePagesStatus) {
	*out = *in
	if in.Pages != nil {
		in, out := &in.Pages, &out.Pages
		*out = make([]HugePageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastAllocationAttempt.DeepCopyInto(&out.LastAllocationAttempt)
	if in.MemoryInfo != nil {
		in, out := &in.MemoryInfo, &out.MemoryInfo
		*out = new(HugePageMemoryInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugePagesStatus.
func (in *HugePagesStatus) DeepCopy() *HugePagesStatus {
	if in == nil {
		return nil
	}
	out := new(HugePagesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KSMConfig) DeepCopyInto(out *KSMConfig) {
	*out = *in
	if in.ScanInterval != nil {
		in, out := &in.ScanInterval, &out.ScanInterval
		*out = new(int32)
		**out = **in
	}
	if in.PagesToScan != nil {
		in, out := &in.PagesToScan, &out.PagesToScan
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KSMConfig.
func (in *KSMConfig) DeepCopy() *KSMConfig {
	if in == nil {
		return nil
	}
	out := new(KSMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KSMStatus) DeepCopyInto(out *KSMStatus) {
	*out = *in
	if in.ScanInterval != nil {
		in, out := &in.ScanInterval, &out.ScanInterval
		*out = new(int32)
		**out = **in
	}
	if in.PagesToScan != nil {
		in, out := &in.PagesToScan, &out.PagesToScan
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KSMStatus.
func (in *KSMStatus) DeepCopy() *KSMStatus {
	if in == nil {
		return nil
	}
	out := new(KSMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelModulesConfig) DeepCopyInto(out *KernelModulesConfig) {
	*out = *in
	if in.Load != nil {
		in, out := &in.Load, &out.Load
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unload != nil {
		in, out := &in.Unload, &out.Unload
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := val
				outVal = make(map[string]string, len(inVal))
				for key, val := range inVal {
					outVal[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelModulesConfig.
func (in *KernelModulesConfig) DeepCopy() *KernelModulesConfig {
	if in == nil {
		return nil
	}
	out := new(KernelModulesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelModulesStatus) DeepCopyInto(out *KernelModulesStatus) {
	*out = *in
	if in.LoadedModules != nil {
		in, out := &in.LoadedModules, &out.LoadedModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnloadedModules != nil {
		in, out := &in.UnloadedModules, &out.UnloadedModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FailedModules != nil {
		in, out := &in.FailedModules, &out.FailedModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelModulesStatus.
func (in *KernelModulesStatus) DeepCopy() *KernelModulesStatus {
	if in == nil {
		return nil
	}
	out := new(KernelModulesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryConfig) DeepCopyInto(out *MemoryConfig) {
	*out = *in
	if in.Swappiness != nil {
		in, out := &in.Swappiness, &out.Swappiness
		*out = new(int32)
		**out = **in
	}
	if in.KSM != nil {
		in, out := &in.KSM, &out.KSM
		*out = new(KSMConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryConfig.
func (in *MemoryConfig) DeepCopy() *MemoryConfig {
	if in == nil {
		return nil
	}
	out := new(MemoryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStatus) DeepCopyInto(out *MemoryStatus) {
	*out = *in
	if in.Swappiness != nil {
		in, out := &in.Swappiness, &out.Swappiness
		*out = new(int32)
		**out = **in
	}
	if in.KSMStatus != nil {
		in, out := &in.KSMStatus, &out.KSMStatus
		*out = new(KSMStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStatus.
func (in *MemoryStatus) DeepCopy() *MemoryStatus {
	if in == nil {
		return nil
	}
	out := new(MemoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMANodeMemoryInfo) DeepCopyInto(out *NUMANodeMemoryInfo) {
	*out = *in
	if in.HugePagesAllocated != nil {
		in, out := &in.HugePagesAllocated, &out.HugePagesAllocated
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMANodeMemoryInfo.
func (in *NUMANodeMemoryInfo) DeepCopy() *NUMANodeMemoryInfo {
	if in == nil {
		return nil
	}
	out := new(NUMANodeMemoryInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENI) DeepCopyInto(out *NodeENI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENI.
func (in *NodeENI) DeepCopy() *NodeENI {
	if in == nil {
		return nil
	}
	out := new(NodeENI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeENI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENIList) DeepCopyInto(out *NodeENIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeENI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENIList.
func (in *NodeENIList) DeepCopy() *NodeENIList {
	if in == nil {
		return nil
	}
	out := new(NodeENIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeENIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENISpec) DeepCopyInto(out *NodeENISpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetNames != nil {
		in, out := &in.SubnetNames, &out.SubnetNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupNames != nil {
		in, out := &in.SecurityGroupNames, &out.SecurityGroupNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENISpec.
func (in *NodeENISpec) DeepCopy() *NodeENISpec {
	if in == nil {
		return nil
	}
	out := new(NodeENISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeENIStatus) DeepCopyInto(out *NodeENIStatus) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]ENIAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeENIStatus.
func (in *NodeENIStatus) DeepCopy() *NodeENIStatus {
	if in == nil {
		return nil
	}
	out := new(NodeENIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfig) DeepCopyInto(out *NodeSystemConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfig.
func (in *NodeSystemConfig) DeepCopy() *NodeSystemConfig {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigList) DeepCopyInto(out *NodeSystemConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSystemConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigList.
func (in *NodeSystemConfigList) DeepCopy() *NodeSystemConfigList {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSystemConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigSpec) DeepCopyInto(out *NodeSystemConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HugePagesConfig != nil {
		in, out := &in.HugePagesConfig, &out.HugePagesConfig
		*out = new(HugePagesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SysctlConfig != nil {
		in, out := &in.SysctlConfig, &out.SysctlConfig
		*out = new(SysctlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelModulesConfig != nil {
		in, out := &in.KernelModulesConfig, &out.KernelModulesConfig
		*out = new(KernelModulesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUConfig != nil {
		in, out := &in.CPUConfig, &out.CPUConfig
		*out = new(CPUConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryConfig != nil {
		in, out := &in.MemoryConfig, &out.MemoryConfig
		*out = new(MemoryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigSpec.
func (in *NodeSystemConfigSpec) DeepCopy() *NodeSystemConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSystemConfigStatus) DeepCopyInto(out *NodeSystemConfigStatus) {
	*out = *in
	if in.Configurations != nil {
		in, out := &in.Configurations, &out.Configurations
		*out = make([]SystemConfigStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSystemConfigStatus.
func (in *NodeSystemConfigStatus) DeepCopy() *NodeSystemConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSystemConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysctlConfig) DeepCopyInto(out *SysctlConfig) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Presets != nil {
		in, out := &in.Presets, &out.Presets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysctlConfig.
func (in *SysctlConfig) DeepCopy() *SysctlConfig {
	if in == nil {
		return nil
	}
	out := new(SysctlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysctlStatus) DeepCopyInto(out *SysctlStatus) {
	*out = *in
	if in.AppliedParameters != nil {
		in, out := &in.AppliedParameters, &out.AppliedParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FailedParameters != nil {
		in, out := &in.FailedParameters, &out.FailedParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysctlStatus.
func (in *SysctlStatus) DeepCopy() *SysctlStatus {
	if in == nil {
		return nil
	}
	out := new(SysctlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemConfigStatus) DeepCopyInto(out *SystemConfigStatus) {
	*out = *in
	if in.HugePagesStatus != nil {
		in, out := &in.HugePagesStatus, &out.HugePagesStatus
		*out = new(HugePagesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SysctlStatus != nil {
		in, out := &in.SysctlStatus, &out.SysctlStatus
		*out = new(SysctlStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelModulesStatus != nil {
		in, out := &in.KernelModulesStatus, &out.KernelModulesStatus
		*out = new(KernelModulesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUStatus != nil {
		in, out := &in.CPUStatus, &out.CPUStatus
		*out = new(CPUStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.MemoryStatus != nil {
		in, out := &in.MemoryStatus, &out.MemoryStatus
		*out = new(MemoryStatus)
		(*in).DeepCopyInto(*out)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemConfigStatus.
func (in *SystemConfigStatus) DeepCopy() *SystemConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SystemConfigStatus)
	in.DeepCopyInto(out)
	return out
}
