apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dpdkconfigs.networking.k8s.aws
spec:
  group: networking.k8s.aws
  names:
    kind: DPDKConfig
    listKind: DPDKConfigList
    plural: dpdkconfigs
    singular: dpdkconfig
    shortNames:
    - dpdk
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nodeSelector:
                type: object
                additionalProperties:
                  type: string
              driverOptions:
                type: object
                properties:
                  enableUnsafeNoIOMMU:
                    type: boolean
                    default: true
                  writeCombining:
                    type: boolean
                    default: false
              resourceMapping:
                type: array
                items:
                  type: object
                  properties:
                    deviceIndex:
                      type: integer
                      minimum: 0
                    resourceName:
                      type: string
                    driver:
                      type: string
                      default: "vfio-pci"
            required:
            - nodeSelector
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              nodesReady:
                type: array
                items:
                  type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp

