apiVersion: batch/v1
kind: Job
metadata:
  name: dpdk-setup
  namespace: eni-controller-system
spec:
  template:
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: dpdk-setup
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Setting up DPDK environment on the host..."

          # Install required packages
          apt-get update && apt-get install -y kmod

          # Load kernel modules
          modprobe vfio || echo "Failed to load vfio module"
          modprobe vfio-pci || echo "Failed to load vfio-pci module"

          # Enable unsafe NOIOMMU mode
          echo 1 > /sys/module/vfio/parameters/enable_unsafe_noiommu_mode || echo "Failed to enable unsafe NOIOMMU mode"

          # Create module load configuration for persistence across reboots
          mkdir -p /etc/modules-load.d
          echo "vfio" > /etc/modules-load.d/dpdk.conf
          echo "vfio-pci" >> /etc/modules-load.d/dpdk.conf
          chmod 644 /etc/modules-load.d/dpdk.conf

          # Create modprobe configuration for persistence across reboots
          mkdir -p /etc/modprobe.d
          echo "options vfio enable_unsafe_noiommu_mode=1" > /etc/modprobe.d/dpdk.conf
          chmod 644 /etc/modprobe.d/dpdk.conf

          echo "DPDK setup completed successfully."
        securityContext:
          privileged: true
      restartPolicy: Never
  backoffLimit: 4
