apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eni-manager
  namespace: eni-controller-system
spec:
  template:
    spec:
      containers:
      - name: eni-manager
        env:
        - name: DEVICE_INDEX_MAPPING
          value: "true"
