apiVersion: apps/v1
kind: Deployment
metadata:
  name: eni-controller
  namespace: eni-controller-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
