apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"eni-controller"},"name":"eni-controller","namespace":"eni-controller-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"eni-controller"}},"template":{"metadata":{"labels":{"app":"eni-controller"}},"spec":{"containers":[{"args":["--metrics-addr=:8080","--enable-leader-election"],"env":[{"name":"COMPONENT","value":"eni-controller"},{"name":"AWS_REGION","value":"us-east-1"},{"name":"MAX_CONCURRENT_ENI_CLEANUP","value":"3"}],"image":"ghcr.io/johnlam90/aws-multi-eni-controller:beta.sandbox-test0-4.360b0e1","name":"manager","resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"serviceAccountName":"eni-controller","terminationGracePeriodSeconds":10}}}}
  creationTimestamp: "2025-05-11T21:23:54Z"
  generation: 3
  labels:
    app: eni-controller
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"manager"}:
                .: {}
                f:args: {}
                f:env:
                  .: {}
                  k:{"name":"AWS_REGION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"COMPONENT"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MAX_CONCURRENT_ENI_CLEANUP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl
    operation: Update
    time: "2025-05-11T22:17:08Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2025-05-11T22:54:26Z"
  name: eni-controller
  namespace: eni-controller-system
  resourceVersion: "8452328"
  uid: afd80c30-c6b1-4c9a-bdf4-288ffbaee459
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eni-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eni-controller
    spec:
      containers:
      - args:
        - --metrics-addr=:8080
        - --enable-leader-election
        env:
        - name: COMPONENT
          value: eni-controller
        - name: AWS_REGION
          value: us-east-1
        - name: MAX_CONCURRENT_ENI_CLEANUP
          value: "3"
        image: ghcr.io/johnlam90/aws-multi-eni-controller:beta.sandbox-test0-4.360b0e1
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: eni-controller
      serviceAccountName: eni-controller
      terminationGracePeriodSeconds: 10
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-11T21:23:54Z"
    lastUpdateTime: "2025-05-11T22:17:10Z"
    message: ReplicaSet "eni-controller-5546d57595" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-05-11T22:54:26Z"
    lastUpdateTime: "2025-05-11T22:54:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
