apiVersion: apps/v1
kind: Deployment
metadata:
  name: eni-controller
  namespace: eni-controller-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: AWS_EC2_SKIP_VERIFY_SSL
          value: "true"
