apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeenis.networking.k8s.aws
spec:
  group: networking.k8s.aws
  names:
    kind: NodeENI
    listKind: NodeENIList
    plural: nodeenis
    shortNames:
    - neni
    singular: nodeeni
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              enableDPDK:
                description: Whether to enable DPDK binding for this ENI
                type: boolean
              dpdkDriver:
                description: DPDK driver to use for binding (e.g., vfio-pci)
                type: string
              dpdkResourceName:
                description: Resource name to use for DPDK device in SRIOV device plugin
                type: string
