apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sriovdp
    tier: node
  name: kube-sriov-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sriov-device-plugin
  template:
    metadata:
      labels:
        app: sriovdp
        name: sriov-device-plugin
        tier: node
    spec:
      containers:
      - args:
        - --log-dir=sriovdp
        - --log-level=10
        image: ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:latest
        imagePullPolicy: IfNotPresent
        name: kube-sriovdp
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
          requests:
            cpu: 250m
            memory: 40Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: devicesock
        - mountPath: /var/lib/kubelet/plugins_registry
          name: plugins-registry
        - mountPath: /var/log
          name: log
        - mountPath: /etc/pcidp
          name: config-volume
        - mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
          name: device-info
      hostNetwork: true
      serviceAccountName: sriov-device-plugin
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: devicesock
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
        name: plugins-registry
      - hostPath:
          path: /var/log
        name: log
      - hostPath:
          path: /var/run/k8s.cni.cncf.io/devinfo/dp
          type: DirectoryOrCreate
        name: device-info
      - hostPath:
          path: /etc/pcidp
          type: DirectoryOrCreate
        name: config-volume
