apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: nodeeni-subnet-a
spec:
  nodeSelector:
    ng: multi-eni
  subnetID: subnet-0f59b4f14737be9ad  # Replace with your subnet ID
  securityGroupIDs:
  - sg-05da196f3314d4af8  # Replace with your security group ID
  deviceIndex: 1
  deleteOnTermination: true
  description: "ENI for subnet A"
---
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: nodeeni-subnet-b
spec:
  nodeSelector:
    ng: multi-eni
  subnetID: subnet-abcdef1234567890  # Replace with your subnet ID
  securityGroupIDs:
  - sg-05da196f3314d4af8  # Replace with your security group ID
  deviceIndex: 2
  deleteOnTermination: true
  description: "ENI for subnet B"
---
# Alternative approach using node labels for subnet selection
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: nodeeni-subnet-a-selector
spec:
  nodeSelector:
    ng: multi-eni
    subnet: a
  subnetID: subnet-0f59b4f14737be9ad  # Replace with your subnet ID
  securityGroupIDs:
  - sg-05da196f3314d4af8  # Replace with your security group ID
  deviceIndex: 1
  deleteOnTermination: true
  description: "ENI for nodes labeled with subnet=a"
---
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: nodeeni-subnet-b-selector
spec:
  nodeSelector:
    ng: multi-eni
    subnet: b
  subnetID: subnet-abcdef1234567890  # Replace with your subnet ID
  securityGroupIDs:
  - sg-05da196f3314d4af8  # Replace with your security group ID
  deviceIndex: 1
  deleteOnTermination: true
  description: "ENI for nodes labeled with subnet=b"
