apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: nodeeni-with-mtu
spec:
  # Select nodes with this label
  nodeSelector:
    ng: multi-eni
  
  # Use either subnetID or subnetName
  # Replace with your actual subnet ID
  subnetID: subnet-0123456789abcdef0
  
  # Security groups to attach to the ENI
  # Replace with your actual security group IDs
  securityGroupIDs:
  - sg-0123456789abcdef0
  
  # Device index for the ENI (1-based)
  deviceIndex: 1
  
  # Whether to delete the ENI when the instance terminates
  deleteOnTermination: true
  
  # Description for the ENI
  description: "Example ENI with custom MTU"
  
  # MTU for the ENI (9000 for jumbo frames)
  mtu: 9000
