apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: example-nodeeni
spec:
  # Select nodes with this label
  nodeSelector:
    ng: multi-eni
  
  # Use either subnetID or subnetName
  # Replace with your actual subnet ID
  subnetID: subnet-0123456789abcdef0
  # Or use a subnet name (AWS tag)
  # subnetName: my-subnet-name
  
  # Security groups to attach to the ENI
  # Replace with your actual security group IDs
  securityGroupIDs:
  - sg-0123456789abcdef0
  
  # Or use security group names (AWS tags)
  # securityGroupNames:
  # - my-security-group-name
  
  # Device index for the ENI (1-based)
  deviceIndex: 1
  
  # Whether to delete the ENI when the instance terminates
  deleteOnTermination: true
  
  # Description for the ENI
  description: "Example ENI created by aws-multi-eni-controller"
