apiVersion: networking.k8s.aws/v1alpha1
kind: NodeENI
metadata:
  name: multus-eni-sg-name
spec:
  nodeSelector:
    ng: multi-eni
  subnetID: subnet-0f59b4f14737be9ad
  securityGroupNames:
  - multus-security-group
  deviceIndex: 2
  deleteOnTermination: true
  description: "Multus ENI using security group name instead of ID"
