apiVersion: apps/v1
kind: Deployment
metadata:
  name: eni-controller
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: aws-multi-eni-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: eni-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eni-controller
  template:
    metadata:
      labels:
        app: eni-controller
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: COMPONENT
          value: "eni-controller"
        - name: AWS_REGION
          value: "{{ .Values.awsRegion }}"
        # AWS SDK configuration for strict IMDSv2 enforcement
        # These settings ensure IMDSv2-only operation for enhanced security
        - name: AWS_EC2_METADATA_DISABLED
          value: "false"
        - name: AWS_EC2_METADATA_V1_DISABLED
          value: "true"
        - name: AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE
          value: "IPv4"
        - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
          value: "http://169.254.169.254"
        # Increased timeout and retry configuration for reliable IMDS calls
        - name: AWS_METADATA_SERVICE_TIMEOUT
          value: "30"
        - name: AWS_METADATA_SERVICE_NUM_ATTEMPTS
          value: "5"
        - name: LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: MAX_CONCURRENT_ENI_CLEANUP
          value: "{{ .Values.controller.maxConcurrentENICleanup }}"
        - name: MAX_CONCURRENT_RECONCILES
          value: "{{ .Values.controller.maxConcurrentReconciles }}"
        {{- if .Values.metrics.enabled }}
        - name: METRICS_PORT
          value: "{{ .Values.metrics.port }}"
        {{- end }}
        args:
        - --metrics-addr={{ .Values.controller.metricsAddr }}
        - --enable-leader-election={{ .Values.controller.enableLeaderElection }}
        resources:
          {{- toYaml .Values.resources.controller | nindent 10 }}
        {{- if .Values.metrics.enabled }}
        ports:
        - name: metrics
          containerPort: {{ .Values.metrics.port }}
          protocol: TCP
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.controller.terminationGracePeriodSeconds }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
