{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: eni-controller-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: aws-multi-eni-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
  - port: {{ .Values.metrics.service.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: eni-controller
{{- end }}
