apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodesystemconfigs.networking.k8s.aws
spec:
  conversion:
    strategy: None
  group: networking.k8s.aws
  names:
    kind: NodeSystemConfig
    listKind: NodeSystemConfigList
    plural: nodesystemconfigs
    shortNames:
    - nsc
    - nsysconfig
    singular: nodesystemconfig
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Number of nodes with system configurations applied
      jsonPath: .status.configurations
      name: Nodes
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              nodeSelector:
                additionalProperties:
                  type: string
                description: Labels to select nodes that should have system configurations applied
                type: object
              hugePagesConfig:
                description: Configuration for huge pages
                properties:
                  enabled:
                    description: Whether huge pages should be configured
                    type: boolean
                  pages:
                    description: Huge pages configuration for different page sizes
                    items:
                      properties:
                        size:
                          description: Huge page size (e.g., "2Mi", "1Gi")
                          type: string
                        count:
                          description: Number of huge pages to allocate
                          type: integer
                        numaNode:
                          description: NUMA node to allocate pages on (optional)
                          type: integer
                      required:
                      - size
                      - count
                      type: object
                    type: array
                  mountPath:
                    description: Path where huge pages should be mounted (default /dev/hugepages)
                    type: string
                  numaAware:
                    description: Whether to configure huge pages in a NUMA-aware manner
                    type: boolean
                required:
                - enabled
                type: object
              sysctlConfig:
                description: Configuration for sysctl parameters
                properties:
                  enabled:
                    description: Whether sysctl parameters should be configured
                    type: boolean
                  parameters:
                    additionalProperties:
                      type: string
                    description: Map of sysctl parameter names to their values
                    type: object
                  presets:
                    description: Predefined sysctl configurations for common use cases
                    items:
                      type: string
                    type: array
                required:
                - enabled
                type: object
              kernelModulesConfig:
                description: Configuration for kernel modules
                properties:
                  enabled:
                    description: Whether kernel modules should be managed
                    type: boolean
                  load:
                    description: List of kernel modules to load
                    items:
                      type: string
                    type: array
                  unload:
                    description: List of kernel modules to unload
                    items:
                      type: string
                    type: array
                  parameters:
                    additionalProperties:
                      additionalProperties:
                        type: string
                      type: object
                    description: Map of module names to their parameters
                    type: object
                required:
                - enabled
                type: object
              cpuConfig:
                description: Configuration for CPU-related optimizations
                properties:
                  enabled:
                    description: Whether CPU optimizations should be applied
                    type: boolean
                  isolatedCPUs:
                    description: CPU cores to isolate for dedicated workloads
                    type: string
                  governor:
                    description: CPU frequency governor to use
                    type: string
                  turboBoost:
                    description: Whether to enable/disable turbo boost
                    type: boolean
                required:
                - enabled
                type: object
              memoryConfig:
                description: Configuration for memory-related optimizations
                properties:
                  enabled:
                    description: Whether memory optimizations should be applied
                    type: boolean
                  swappiness:
                    description: Kernel swappiness value (0-100)
                    type: integer
                    minimum: 0
                    maximum: 100
                  transparentHugePages:
                    description: Transparent huge pages configuration
                    type: string
                  ksm:
                    description: Kernel Samepage Merging configuration
                    properties:
                      enabled:
                        description: Whether KSM should be enabled
                        type: boolean
                      scanInterval:
                        description: Scan interval in milliseconds
                        type: integer
                      pagesToScan:
                        description: Number of pages to scan per interval
                        type: integer
                    required:
                    - enabled
                    type: object
                required:
                - enabled
                type: object
            required:
            - nodeSelector
            type: object
          status:
            properties:
              configurations:
                description: List of system configurations applied to nodes
                items:
                  properties:
                    nodeID:
                      description: ID of the node
                      type: string
                    nodeName:
                      description: Name of the node
                      type: string
                    hugePagesStatus:
                      description: Status of huge pages configuration
                      properties:
                        configured:
                          description: Whether huge pages are configured
                          type: boolean
                        pages:
                          description: Status of each configured page size
                          items:
                            properties:
                              size:
                                description: Huge page size
                                type: string
                              requested:
                                description: Number of pages requested
                                type: integer
                              allocated:
                                description: Number of pages actually allocated
                                type: integer
                              available:
                                description: Number of pages available for use
                                type: integer
                              numaNode:
                                description: NUMA node where pages are allocated
                                type: integer
                            required:
                            - size
                            - requested
                            - allocated
                            - available
                            type: object
                          type: array
                        mountPath:
                          description: Actual mount path used
                          type: string
                        totalAllocated:
                          description: Total number of huge pages allocated
                          type: integer
                        totalAvailable:
                          description: Total number of huge pages available
                          type: integer
                      required:
                      - configured
                      type: object
                    sysctlStatus:
                      description: Status of sysctl configuration
                      properties:
                        configured:
                          description: Whether sysctl parameters are configured
                          type: boolean
                        appliedParameters:
                          additionalProperties:
                            type: string
                          description: Actually applied sysctl parameters
                          type: object
                        failedParameters:
                          additionalProperties:
                            type: string
                          description: Parameters that failed to apply
                          type: object
                      required:
                      - configured
                      type: object
                    kernelModulesStatus:
                      description: Status of kernel modules configuration
                      properties:
                        configured:
                          description: Whether kernel modules are configured
                          type: boolean
                        loadedModules:
                          description: List of successfully loaded modules
                          items:
                            type: string
                          type: array
                        unloadedModules:
                          description: List of successfully unloaded modules
                          items:
                            type: string
                          type: array
                        failedModules:
                          description: Modules that failed to load/unload
                          items:
                            type: string
                          type: array
                      required:
                      - configured
                      type: object
                    cpuStatus:
                      description: Status of CPU configuration
                      properties:
                        configured:
                          description: Whether CPU optimizations are configured
                          type: boolean
                        isolatedCPUs:
                          description: Actually isolated CPU cores
                          type: string
                        governor:
                          description: Current CPU frequency governor
                          type: string
                        turboBoost:
                          description: Current turbo boost status
                          type: boolean
                      required:
                      - configured
                      type: object
                    memoryStatus:
                      description: Status of memory configuration
                      properties:
                        configured:
                          description: Whether memory optimizations are configured
                          type: boolean
                        swappiness:
                          description: Current swappiness value
                          type: integer
                        transparentHugePages:
                          description: Current THP setting
                          type: string
                        ksmStatus:
                          description: Current KSM configuration
                          properties:
                            enabled:
                              description: Whether KSM is enabled
                              type: boolean
                            scanInterval:
                              description: Current scan interval
                              type: integer
                            pagesToScan:
                              description: Current pages to scan setting
                              type: integer
                          required:
                          - enabled
                          type: object
                      required:
                      - configured
                      type: object
                    overallStatus:
                      description: Overall status of the configuration
                      type: string
                    lastUpdated:
                      description: Timestamp of the last update
                      format: date-time
                      type: string
                    message:
                      description: Additional information about the configuration status
                      type: string
                  required:
                  - nodeID
                  - nodeName
                  - overallStatus
                  - lastUpdated
                  type: object
                type: array
              lastUpdated:
                description: Timestamp of the last status update
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
