apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eni-manager
  namespace: eni-controller-system
  labels:
    app: eni-manager
spec:
  selector:
    matchLabels:
      app: eni-manager
  template:
    metadata:
      labels:
        app: eni-manager
    spec:
      serviceAccountName: eni-controller
      hostNetwork: true
      nodeSelector:
        ng: multi-eni
      containers:
      - name: eni-manager
        image:  ghcr.io/johnlam90/aws-multi-eni-controller:v1.3.0
        env:
        - name: COMPONENT
          value: "eni-manager"
        - name: DEFAULT_MTU
          value: "0"  # Set to 0 to use MTU from NodeENI resources
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AWS_REGION
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
              # This is a placeholder - in a real deployment, you would use a configmap or
              # the downward API to get the AWS region
        # DPDK Configuration
        - name: ENABLE_DPDK
          value: "false"  # Set to true to enable DPDK device binding
        - name: DEFAULT_DPDK_DRIVER
          value: "vfio-pci"  # Default DPDK driver to use
        - name: DPDK_BINDING_SCRIPT
          value: "/opt/dpdk/dpdk-devbind.py"  # Path to DPDK binding script
        - name: SRIOV_DP_CONFIG_PATH
          value: "/etc/pcidp/config.json"  # Path to SRIOV device plugin config
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        args:
        - --check-interval=30s
        - --debug=true
        - --eni-pattern=^(eth|ens|eni|en)[0-9]+
        - --ignore-interfaces=tunl0,gre0,gretap0,erspan0,ip_vti0,ip6_vti0,sit0,ip6tnl0,ip6gre0
        - --use-netlink=true
        # Primary interface will be auto-detected
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: host-sys
          mountPath: /host/sys
        - name: host-proc
          mountPath: /host/proc
        - name: host-run
          mountPath: /host/run
        - name: dpdk-tools
          mountPath: /opt/dpdk
        - name: sriov-dp-config
          mountPath: /etc/pcidp
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-run
        hostPath:
          path: /run
      - name: dpdk-tools
        hostPath:
          path: /opt/dpdk
          type: DirectoryOrCreate
      - name: sriov-dp-config
        hostPath:
          path: /etc/pcidp
          type: DirectoryOrCreate
