apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-05-13T04:35:38Z"
  generation: 1
  name: nodeenis.networking.k8s.aws
  resourceVersion: "8923464"
  uid: 0c1146ca-e186-4832-bd83-e47fb940d383
spec:
  conversion:
    strategy: None
  group: networking.k8s.aws
  names:
    kind: NodeENI
    listKind: NodeENIList
    plural: nodeenis
    shortNames:
    - neni
    singular: nodeeni
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Number of nodes with ENIs attached
      jsonPath: .status.attachments
      name: Nodes
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              deleteOnTermination:
                default: true
                description: Whether to delete the ENI when the node is terminated
                type: boolean
              description:
                description: Description for the ENI
                type: string
              deviceIndex:
                default: 1
                description: 'Device index for the ENI (default: 1)'
                type: integer
              interfaceName:
                description: 'Explicit interface name to use for this ENI (e.g., eth2)'
                type: string
              mtu:
                description: Maximum Transmission Unit (MTU) for the ENI (default
                  system default)
                type: integer
              nodeSelector:
                additionalProperties:
                  type: string
                description: Labels to select nodes that should have ENIs attached
                type: object
              securityGroupIDs:
                description: AWS Security Group IDs to attach to the ENI
                items:
                  type: string
                type: array
              securityGroupNames:
                description: AWS Security Group Names to attach to the ENI (used if
                  securityGroupIDs is not provided)
                items:
                  type: string
                type: array
              subnetID:
                description: AWS Subnet ID where the ENI should be created
                type: string
              subnetIDs:
                description: List of AWS Subnet IDs where the ENI can be created (one
                  will be selected)
                items:
                  type: string
                type: array
              subnetName:
                description: AWS Subnet Name where the ENI should be created (used
                  if subnetID is not provided)
                type: string
              subnetNames:
                description: List of AWS Subnet Names where the ENI can be created
                  (one will be selected)
                items:
                  type: string
                type: array
              enableDPDK:
                description: Whether to enable DPDK binding for this ENI
                type: boolean
              dpdkDriver:
                description: DPDK driver to use for binding (e.g., vfio-pci)
                type: string
              dpdkResourceName:
                description: Resource name to use for DPDK device in SRIOV device plugin
                type: string
            required:
            - nodeSelector
            type: object
          status:
            properties:
              attachments:
                items:
                  properties:
                    attachmentID:
                      description: ID of the ENI attachment
                      type: string
                    deviceIndex:
                      description: Device index used for this ENI attachment
                      type: integer
                    eniID:
                      description: ID of the attached ENI
                      type: string
                    instanceID:
                      description: EC2 instance ID
                      type: string
                    lastUpdated:
                      description: Timestamp of the last update
                      format: date-time
                      type: string
                    mtu:
                      description: Maximum Transmission Unit (MTU) configured for
                        the ENI
                      type: integer
                    nodeID:
                      description: ID of the node
                      type: string
                    status:
                      description: Status of the attachment
                      type: string
                    subnetCIDR:
                      description: CIDR block of the subnet where the ENI was created
                      type: string
                    subnetID:
                      description: ID of the subnet where the ENI was created
                      type: string
                    dpdkBound:
                      description: Whether the ENI is bound to a DPDK driver
                      type: boolean
                    dpdkDriver:
                      description: DPDK driver used for binding
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

