apiVersion: networking.k8s.aws/v1alpha1
kind: NodeSystemConfig
metadata:
  name: high-performance-networking
spec:
  nodeSelector:
    networking: high-performance
  sysctlConfig:
    enabled: true
    presets:
      - "high-performance-networking"
      - "low-latency"
    parameters:
      net.core.rmem_max: "268435456"
      net.core.wmem_max: "268435456"
      net.ipv4.tcp_congestion_control: "bbr"
  cpuConfig:
    enabled: true
    isolatedCPUs: "2-7,10-15"
    governor: "performance"
    turboBoost: true
  memoryConfig:
    enabled: true
    swappiness: 1
    transparentHugePages: "never"
    ksm:
      enabled: false
---
apiVersion: networking.k8s.aws/v1alpha1
kind: NodeSystemConfig
metadata:
  name: memory-optimized
spec:
  nodeSelector:
    workload: memory-intensive
  memoryConfig:
    enabled: true
    swappiness: 10
    transparentHugePages: "madvise"
    ksm:
      enabled: true
      scanInterval: 100
      pagesToScan: 1000
  sysctlConfig:
    enabled: true
    parameters:
      vm.dirty_ratio: "15"
      vm.dirty_background_ratio: "5"
      vm.vfs_cache_pressure: "50"
