apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "sriov",
          "resourcePrefix": "intel.com",
          "selectors": [
            {

              "drivers": ["vfio-pci"],
              "pciAddresses": ["0000:00:07.0"]
            }
          ]
        }
      ]
    }
