apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.3.5"
appVersion: "v1.3.5"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
  - dpdk
  - security
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.3.5
    - Fix ENI Manager incorrectly generating SR-IOV config for regular ENI configurations
    - Implement proper PCI address mapping for SR-IOV configurations
    - Prioritize PCI address matching over device index for SR-IOV interfaces
    - Add comprehensive test coverage for interface-to-NodeENI mapping
    - Resolve PCI address mismatches in SR-IOV device plugin configuration
    - Improve separation between regular ENI and SR-IOV functionality
    - Add detailed logging for interface mapping decisions
    - Fix issue where regular ENI configs triggered unnecessary SR-IOV operations
