apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: 0.2.0
appVersion: "v1.2.0"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Add netlink subscription mode for improved interface detection
    - Add multi-architecture support for Docker builds (amd64, arm64)
    - Enhance ENI manager configuration options
    - Improve error handling for ENI attachments
    - Add support for security group names in NodeENI resources
