apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.2.9"
appVersion: "v1.2.9"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.2.9
    - Add device index tracking to ENI attachments for better reconciliation
    - Ensure consistent device index to subnet mapping across all nodes
    - Improve handling of manually detached ENIs
    - Refactor code to reduce cyclomatic complexity
    - Enhance controller stability and reliability
