apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.26"
appVersion: "v1.26"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.26
    - Add MAX_CONCURRENT_RECONCILES parameter for better scaling
    - Improve MTU configuration for all interfaces
    - Optimize Docker build process
    - Fix code quality issues and reduce cyclomatic complexity
    - Improve error handling and logging
