apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.3.7"
appVersion: "v1.3.6-comprehensive-tests"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
  - dpdk
  - security
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.3.7 with comprehensive test suite
    - Fix ens8 interface device index calculation (ens_number - 5 formula)
    - Implement robust hybrid device index calculation (sysfs + fallback)
    - Add comprehensive unit tests for device index calculation logic
    - Support scalability testing for 10+ ENI interfaces per node
    - Add cross-platform compatibility for Amazon Linux 2 vs 2023
    - Implement concurrent device index lookup performance testing
    - Add error handling and graceful degradation for sysfs failures
    - Include NodeENI integration testing and regression prevention
    - Performance benchmarks: 2.6M+ operations/second for device index calculation
