apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.2.8"
appVersion: "v1.2.8"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.2.8
    - Add library support for programmatic ENI management
    - Update Go module to support Go 1.22+
    - Improve documentation for library usage
    - Add example code for using as a library
    - Fix package naming to comply with Go style guide
