apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.3.1"
appVersion: "v1.3.1"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.3.1
    - Add dpdkPCIAddress field to NodeENI CRD for direct device targeting
    - Fix DPDK binding logic to respect enableDPDK field
    - Improve DPDK device binding reliability by using PCI addresses
    - Fix issue with DPDK binding when enableDPDK is false
    - Enhance DPDK status tracking in NodeENI resources
