apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: 0.3.2
appVersion: "v1.2.4"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Refactor verifyENIAttachments to reduce cyclomatic complexity
    - Improve code maintainability by breaking down complex functions
    - Enhance error handling for ENI attachment verification
    - Fix code quality issues identified by gocyclo
    - Maintain all functionality while improving code structure
