apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: 0.3.3
appVersion: "v1.2.5"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Add configurable MTU option for ENIs in NodeENI resources
    - Implement MTU configuration in ENI Manager
    - Update ENI attachment status to include MTU information
    - Fix code quality issues and reduce cyclomatic complexity
    - Improve error handling and logging for MTU configuration
