apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.3.6"
appVersion: "v1.3.6"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
  - dpdk
  - security
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.3.6
    - Fix automatic node replacement recovery for IMDSv2 environments
    - Implement multi-strategy IMDS hop limit configuration
    - Add private IP-based instance ID discovery for new nodes
    - Enable VPC-wide IMDS configuration as fallback strategy
    - Add background IMDS configuration retry mechanism
    - Resolve chicken-and-egg problem with IMDS access on new instances
    - Support automatic recovery without manual intervention
    - Add aggressive IMDS configuration option for node replacement scenarios
