apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: 0.3.1
appVersion: "v1.2.3"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Improve detection of manually detached ENIs to avoid manual intervention
    - Enhance ENI attachment verification to be more reliable
    - Add more robust checks for ENI attachment status
    - Fix issue where controller would not detect manually detached ENIs
    - Update subnet CIDR display in ENI attachment status
