apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.2.7"
appVersion: "v1.2.7"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.2.7
    - Optimize AWS API calls with caching for subnet and security group information
    - Improve parallel cleanup implementation with worker pool pattern
    - Optimize interface monitoring with caching for pattern matching
    - Streamline MTU configuration logic
    - Reduce verbose logging in performance-critical paths
