apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: 0.3.0
appVersion: "v1.2.2"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Add subnet CIDR display in ENI attachment status
    - Add support for MAX_CONCURRENT_ENI_CLEANUP environment variable
    - Update CRD to include SubnetCIDR field
    - Improve error handling for ENI cleanup operations
    - Update documentation for new features
