apiVersion: v2
name: aws-multi-eni-controller
description: A Helm chart for AWS Multi-ENI Controller
type: application
version: "1.3.6"
appVersion: "v1.3.2"
home: https://github.com/johnlam90/aws-multi-eni-controller
sources:
  - https://github.com/johnlam90/aws-multi-eni-controller
maintainers:
  - name: John Lam
    email: johnlam90@gmail.com
keywords:
  - aws
  - eni
  - kubernetes
  - networking
  - dpdk
  - security
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Update version to v1.3.6
    - Fix bash compatibility issue in DPDK operations
    - Replace bash with sh for ENI Manager container compatibility
    - Resolve "bash: executable file not found" errors during DPDK unbinding
    - Update controller image to v1.4.0-bash-fix
    - Complete fix for DPDK cleanup operations
