name: Package and Publish Helm Chart

on:
  push:
    branches: [ main ]
    # Trigger on tags for releases
    tags: [ 'v*' ]
    paths:
      - 'charts/**'
  # Allow manual triggering with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version (e.g., 0.1.0)'
        required: true
        default: '0.1.0'
      appVersion:
        description: 'App version (e.g., v1.1.1)'
        required: true
        default: 'v1.1.1'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
      packages: write
      # Add additional permissions for package management
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update Chart version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Update Chart.yaml with the provided version and appVersion
          sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/" charts/aws-multi-eni-controller/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ github.event.inputs.appVersion }}\"/" charts/aws-multi-eni-controller/Chart.yaml

          # Display the updated Chart.yaml
          echo "Updated Chart.yaml:"
          cat charts/aws-multi-eni-controller/Chart.yaml

      - name: Package Helm chart
        run: |
          mkdir -p .helm-charts
          helm package charts/aws-multi-eni-controller -d .helm-charts

          # Get the chart version
          CHART_VERSION=$(grep "^version:" charts/aws-multi-eni-controller/Chart.yaml | awk '{print $2}')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Create Helm repository index
        run: |
          # Create a simple index file for the chart
          helm repo index .helm-charts --url https://github.com/${{ github.repository }}/releases/download/helm-chart-${{ env.CHART_VERSION }}/

      - name: Create GitHub Release for Helm Chart
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: helm-chart-${{ env.CHART_VERSION }}
          name: Helm Chart ${{ env.CHART_VERSION }}
          body: |
            # AWS Multi-ENI Controller Helm Chart ${{ env.CHART_VERSION }}

            This release contains the Helm chart for AWS Multi-ENI Controller.

            ## Installation

            ```bash
            # Download the chart
            wget https://github.com/${{ github.repository }}/releases/download/helm-chart-${{ env.CHART_VERSION }}/aws-multi-eni-controller-${{ env.CHART_VERSION }}.tgz

            # Install the chart
            helm install my-release ./aws-multi-eni-controller-${{ env.CHART_VERSION }}.tgz
            ```

            ## Configuration

            See the [Helm Chart README](https://github.com/${{ github.repository }}/blob/main/charts/aws-multi-eni-controller/README.md) for configuration options.
          files: |
            .helm-charts/*.tgz
            .helm-charts/index.yaml
          draft: false
          prerelease: false

      - name: Display instructions for using the Helm chart
        run: |
          echo "::notice::Helm chart has been published as a GitHub Release."
          echo "::notice::To use the chart, download it from:"
          echo "::notice::https://github.com/${{ github.repository }}/releases/download/helm-chart-${{ env.CHART_VERSION }}/aws-multi-eni-controller-${{ env.CHART_VERSION }}.tgz"
          echo "::notice::Then install the chart with:"
          echo "::notice::helm install my-release ./aws-multi-eni-controller-${{ env.CHART_VERSION }}.tgz"
