name: Package and Publish Helm Chart

on:
  push:
    branches: [ main ]
    # Trigger on tags for releases
    tags: [ 'v*' ]
    paths:
      - 'charts/**'
  # Allow manual triggering with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version (e.g., 0.1.0)'
        required: true
        default: '0.1.0'
      appVersion:
        description: 'App version (e.g., v1.1.1)'
        required: true
        default: 'v1.1.1'

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
      packages: write
      # Add additional permissions for package management
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update Chart version if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          # Update Chart.yaml with the provided version and appVersion
          sed -i "s/^version:.*/version: ${{ github.event.inputs.version }}/" charts/aws-multi-eni-controller/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${{ github.event.inputs.appVersion }}\"/" charts/aws-multi-eni-controller/Chart.yaml
          
          # Display the updated Chart.yaml
          echo "Updated Chart.yaml:"
          cat charts/aws-multi-eni-controller/Chart.yaml

      - name: Package Helm chart
        run: |
          mkdir -p .helm-charts
          helm package charts/aws-multi-eni-controller -d .helm-charts

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Create Helm repository index
        run: |
          # If there's an existing index.yaml, download it first
          if curl -s -f -o index.yaml https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.yaml; then
            echo "Existing index.yaml found, merging with new chart"
            helm repo index .helm-charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/ --merge index.yaml
          else
            echo "No existing index.yaml found, creating new index"
            helm repo index .helm-charts --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          fi
          
          # Move the index to the charts directory
          mv .helm-charts/index.yaml .

      - name: Upload chart as release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: .helm-charts/*.tgz
          generate_release_notes: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
          
      - name: Display instructions for using the Helm chart
        run: |
          echo "::notice::Helm chart has been published to GitHub Pages."
          echo "::notice::To use the chart, add the repository with:"
          echo "::notice::helm repo add aws-multi-eni-controller https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "::notice::Then install the chart with:"
          echo "::notice::helm install my-release aws-multi-eni-controller/aws-multi-eni-controller"
